### PR TITLE
Adding support for reading table into ParquetFile

### PR DESCRIPTION
**Pull request by raghumdani**
[Motivation] #162

Testing
-----

```python
delta_result = DS.list_deltas(namespace=namespace, 
...                         table_name=table_name, 
...                         partition_values=ordered_partition_values, 
...                         table_version=table_version, 
...                         include_manifest=True,
...                         equivalent_table_types=[])

delta = delta_result.read_page()[0]

table = DS.download_delta_manifest_entry(delta, 0, TableType.PYARROW_PARQUET)
# <pyarrow.parquet.core.ParquetFile object at 0xffffa168c100>
```

### CODE REVIEW

**Comment by raghumdani** [comment]
The repartition tests are failing due to a usage of `float("inf")` for comparison in `Expression`. @valiantljk is working on fixings these tests.

**Comment by Zyiqin-Miranda** [comment]
Looks good overall! Just one quick question:
Could you explain why we don't have to support the `input_file_init` for different `content_encoding` as [here](https://github.com/ray-project/deltacat/blob/main/deltacat/utils/pyarrow.py#L259)?

**Comment by raghumdani** [comment]
@Zyiqin-Miranda Good question. The creation of ParquetFile instance does not lead to file read. Content encoding is used to decode the file bytes (i.e., after the file has been downloaded) but in our file has not yet been downloaded. The assumption is that pyarrow library should be capable of decoding appropriate encodings.

**Comment by Zyiqin-Miranda** [comment]
> @Zyiqin-Miranda Good question. The creation of ParquetFile instance does not lead to file read. Content encoding is used to decode the file bytes (i.e., after the file has been downloaded) but in our case file has not yet been downloaded. The assumption is that pyarrow library should be capable of decoding appropriate encodings.

Thanks for the explanation. So to actually read the table, we need to use something like `parquet_file.read()` and assume that the file will be decoded appropriately?

**Comment by raghumdani** [comment]
> > @Zyiqin-Miranda Good question. The creation of ParquetFile instance does not lead to file read. Content encoding is used to decode the file bytes (i.e., after the file has been downloaded) but in our case file has not yet been downloaded. The assumption is that pyarrow library should be capable of decoding appropriate encodings.
> 
> Thanks for the explanation. So to actually read the table, we need to use something like `parquet_file.read()` and assume that the file will be decoded appropriately?

Yes.

**Review by Zyiqin-Miranda — APPROVED** [review]

**Comment by raghumdani** [comment]
Screen Shot 2023-07-31 at 7 37 04 PM

Here is the performance comparison between using `pyarrow.fs.S3FileSystem` vs `s3fs.S3FileSystem`. Overall, the performance is almost the same (looking at median) however s3fs provides capability to easily pass the `s3_client_kwargs` which might be handy in future while `pyarrow.fs.S3FileSystem` does not.

**Pull request merged**
