### PR TITLE
Downgrade Daft and patch version 0.2.11

### PR DESCRIPTION
**Pull request by raghumdani**

### CODE REVIEW

**Review by Zyiqin-Miranda — APPROVED** [review]
LGTM!

**Comment by samster25** [comment]
@raghumdani This PR https://github.com/ray-project/deltacat/pull/274 should prevent API calls hitting the local IMDS (with version `getdaft>=0.2.15` which we think caused the DNS errors you were seeing. I believe deltacat/main is currently at `getdaft==0.2.16` which should be compatible with this change. I also made a PR that upgrades daft the latest [here](https://github.com/ray-project/deltacat/pull/275) but you shouldn't need it to test the fix.

**Comment by pfaraone** [comment]
Is this PR still relevant?

**Comment by raghumdani** [comment]
No, cancelling this.

**Pull request closed without merging**
